"""Create or update the document chat's Knowledge Assistant and Supervisor Agent, idempotently.

Find-or-create by display name, update drifted descriptions and instructions, and attach the KA and
the chat UC functions (created by the bootstrap's create_chat_functions task) as Supervisor tools.
Nothing is deleted: unexpected tools and a KA source pointing elsewhere are reported, not removed.
Serving endpoint names are generated by Databricks, so they are read back and printed.

Uses the Agent Bricks REST API (/api/2.1/knowledge-assistants, /api/2.1/supervisor-agents, Beta),
with the shapes recorded in docs/planning/IMPLEMENTATION_PLAN.md gate G7.
"""

from __future__ import annotations

import argparse
import json
import re
from dataclasses import dataclass, field
from typing import Any

SIMPLE_IDENTIFIER = re.compile(r"^[A-Za-z_][A-Za-z0-9_]{0,127}$")
RESOURCE_NAME = re.compile(r"^[a-z0-9][a-z0-9-]{0,62}$")
VOLUME_DIRECTORY = re.compile(
    r"^/Volumes/[A-Za-z0-9_]+/[A-Za-z0-9_]+/[A-Za-z0-9_]+/[A-Za-z0-9_/-]*/$"
)

KA_DESCRIPTION = (
    "Answers questions about the contents of documents processed by the IDP app."
)
KA_INSTRUCTIONS = (
    "Answer only from the documents. Cite the source file for every claim. The documents are "
    "invoices and government forms. If the documents do not contain the answer, or you are "
    "unsure, say so instead of guessing."
)
SUPERVISOR_DESCRIPTION = (
    "Answers questions about IDP documents and their extracted data."
)
SUPERVISOR_INSTRUCTIONS = (
    "Use the function tools for exact questions: totals, counts, lists of documents, and the "
    "values extracted from a document. Use the documents knowledge assistant for questions "
    "about what a document says. When a tool returns extracted values, show them as a table with "
    "the document's file name, the field and the value. Never add amounts in different "
    "currencies together. Extracted values are model output and have not been approved; say so "
    "when it matters. Source files are named <document_id>.pdf; name a document by its original "
    "file name, which the document_fields tool returns for a document id. Do not show raw ids "
    "unless asked."
)
SOURCE_DISPLAY_NAME = "incoming"

# Tool id -> (function suffix, description). The suffix follows <table_prefix>_.
FUNCTION_TOOLS: dict[str, tuple[str, str]] = {
    "document_fields": (
        "chat_document_fields",
        "All extracted field values of one document, by document id or exact file name.",
    ),
    "find_documents": (
        "chat_find_documents",
        "Documents whose extracted field (e.g. seller_name or payee_organization) contains text.",
    ),
    "invoices": (
        "chat_invoices",
        "Extracted invoices, optionally filtered by supplier and invoice date range.",
    ),
    "invoice_totals": (
        "chat_invoice_totals",
        "Invoice totals per supplier and currency, optionally filtered by supplier and dates.",
    ),
    "case_documents": (
        "chat_case_documents",
        "Documents registered under one case id.",
    ),
}
KA_TOOL_ID = "documents"
KA_TOOL_DESCRIPTION = "Searches the full text of the IDP documents and answers questions about their contents."


@dataclass(frozen=True)
class Settings:
    app_name: str
    target: str
    catalog: str
    project_schema: str
    table_prefix: str
    source_path: str
    with_knowledge_assistant: bool = True

    @property
    def ka_name(self) -> str:
        return f"{self.app_name}-{self.target}-documents-ka"

    @property
    def supervisor_name(self) -> str:
        return f"{self.app_name}-{self.target}-chat-supervisor"

    def function_name(self, suffix: str) -> str:
        return f"{self.catalog}.{self.project_schema}.{self.table_prefix}_{suffix}"


def validate_settings(settings: Settings) -> None:
    if any(
        RESOURCE_NAME.fullmatch(value) is None
        for value in (settings.app_name, settings.target)
    ):
        raise ValueError(
            "App name and target must be lowercase letters, digits and hyphens"
        )
    identifiers = (settings.catalog, settings.project_schema, settings.table_prefix)
    if any(SIMPLE_IDENTIFIER.fullmatch(value) is None for value in identifiers):
        raise ValueError("Catalog, schema and table prefix must be simple identifiers")
    if (
        VOLUME_DIRECTORY.fullmatch(settings.source_path) is None
        or ".." in settings.source_path
    ):
        raise ValueError(
            "The KA source must be a /Volumes/<catalog>/<schema>/<volume>/.../ folder"
        )


@dataclass
class Report:
    dry_run: bool
    actions: list[str] = field(default_factory=list)
    warnings: list[str] = field(default_factory=list)
    endpoints: dict[str, str | None] = field(default_factory=dict)


class Provisioner:
    def __init__(self, client: Any, settings: Settings, dry_run: bool) -> None:
        self.api = client.api_client
        self.settings = settings
        self.report = Report(dry_run=dry_run)

    def run(self) -> Report:
        ka = (
            self._knowledge_assistant()
            if self.settings.with_knowledge_assistant
            else None
        )
        self._supervisor(ka)
        return self.report

    # Knowledge Assistant ---------------------------------------------------------------------

    def _knowledge_assistant(self) -> dict[str, Any] | None:
        desired = {
            "display_name": self.settings.ka_name,
            "description": KA_DESCRIPTION,
            "instructions": KA_INSTRUCTIONS,
        }
        ka = self._find(
            "/api/2.1/knowledge-assistants", "knowledge_assistants", desired
        )
        ka = self._create_or_update(
            ka, "/api/2.1/knowledge-assistants", desired, "knowledge assistant"
        )
        self.report.endpoints["knowledge_assistant"] = (
            ka.get("endpoint_name") if ka else None
        )
        if ka is None:
            self.report.actions.append(f"create knowledge source {SOURCE_DISPLAY_NAME}")
            return None
        self._knowledge_source(ka)
        return ka

    def _knowledge_source(self, ka: dict[str, Any]) -> None:
        path = self.settings.source_path
        parent = f"/api/2.1/{ka['name']}/knowledge-sources"
        sources = self._list(parent, "knowledge_sources")
        existing = next(
            (s for s in sources if s.get("display_name") == SOURCE_DISPLAY_NAME), None
        )
        if existing is None:
            self._write(
                f"create knowledge source {SOURCE_DISPLAY_NAME} -> {path}",
                "POST",
                parent,
                body={
                    "display_name": SOURCE_DISPLAY_NAME,
                    "description": "Documents registered by the IDP app (source volume).",
                    "source_type": "files",
                    "files": {"path": path},
                },
            )
        elif (existing.get("files") or {}).get("path") != path:
            self.report.warnings.append(
                f"knowledge source {SOURCE_DISPLAY_NAME} reads "
                f"{(existing.get('files') or {}).get('path')}, not {path}; left unchanged"
            )

    # Supervisor ------------------------------------------------------------------------------

    def _supervisor(self, ka: dict[str, Any] | None) -> None:
        desired = {
            "display_name": self.settings.supervisor_name,
            "description": SUPERVISOR_DESCRIPTION,
            "instructions": SUPERVISOR_INSTRUCTIONS,
        }
        supervisor = self._find(
            "/api/2.1/supervisor-agents", "supervisor_agents", desired
        )
        supervisor = self._create_or_update(
            supervisor, "/api/2.1/supervisor-agents", desired, "supervisor agent"
        )
        self.report.endpoints["supervisor"] = (
            supervisor.get("endpoint_name") if supervisor else None
        )
        tools = self._desired_tools(ka)
        if supervisor is None:
            for tool_id in tools:
                self.report.actions.append(f"create tool {tool_id}")
            return
        parent = f"/api/2.1/{supervisor['name']}/tools"
        existing = {tool.get("tool_id"): tool for tool in self._list(parent, "tools")}
        for tool_id, tool in tools.items():
            current = existing.pop(tool_id, None)
            if current is None:
                self._write(
                    f"create tool {tool_id}",
                    "POST",
                    parent,
                    query={"tool_id": tool_id},
                    body=tool,
                )
                continue
            kind = tool["tool_type"]
            if current.get("tool_type") != kind or not _same_target(
                current.get(kind), tool[kind]
            ):
                self.report.warnings.append(
                    f"tool {tool_id} points at {current.get(kind)}, not {tool[kind]}; left unchanged"
                )
            elif current.get("description") != tool["description"]:
                self._write(
                    f"update tool {tool_id} description",
                    "PATCH",
                    f"/api/2.1/{current['name']}",
                    query={"update_mask": "description"},
                    body={
                        "tool_type": kind,
                        "description": tool["description"],
                        kind: tool[kind],
                    },
                )
        for unexpected in existing:
            self.report.warnings.append(f"unexpected tool {unexpected} left in place")

    def _desired_tools(self, ka: dict[str, Any] | None) -> dict[str, dict[str, Any]]:
        tools: dict[str, dict[str, Any]] = {}
        if self.settings.with_knowledge_assistant:
            tools[KA_TOOL_ID] = {
                "tool_type": "knowledge_assistant",
                "description": KA_TOOL_DESCRIPTION,
                "knowledge_assistant": {
                    "knowledge_assistant_id": ka["id"] if ka else None
                },
            }
        for tool_id, (suffix, description) in FUNCTION_TOOLS.items():
            tools[tool_id] = {
                "tool_type": "uc_function",
                "description": description,
                "uc_function": {"name": self.settings.function_name(suffix)},
            }
        return tools

    # Shared ----------------------------------------------------------------------------------

    def _find(
        self, path: str, key: str, desired: dict[str, str]
    ) -> dict[str, Any] | None:
        matches = [
            item
            for item in self._list(path, key)
            if item.get("display_name") == desired["display_name"]
        ]
        if len(matches) > 1:
            raise ValueError(f"More than one {key} named {desired['display_name']}")
        return matches[0] if matches else None

    def _create_or_update(
        self,
        current: dict[str, Any] | None,
        path: str,
        desired: dict[str, str],
        label: str,
    ) -> dict[str, Any] | None:
        name = desired["display_name"]
        if current is None:
            return self._write(f"create {label} {name}", "POST", path, body=desired)
        drifted = [
            key
            for key in ("description", "instructions")
            if current.get(key) != desired[key]
        ]
        if drifted:
            updated = self._write(
                f"update {label} {name}: {', '.join(drifted)}",
                "PATCH",
                f"/api/2.1/{current['name']}",
                query={"update_mask": ",".join(drifted)},
                body={key: desired[key] for key in ("display_name", *drifted)},
            )
            return updated or current
        return current

    def _list(self, path: str, key: str) -> list[dict[str, Any]]:
        items: list[dict[str, Any]] = []
        query: dict[str, Any] = {"page_size": 100}
        for _ in range(50):  # bounded pagination
            page = self.api.do("GET", path, query=query) or {}
            items.extend(page.get(key, []))
            token = page.get("next_page_token")
            if not token:
                return items
            query = {"page_size": 100, "page_token": token}
        raise ValueError(f"Too many pages listing {path}")

    def _write(
        self,
        action: str,
        method: str,
        path: str,
        *,
        body: dict[str, Any],
        query: dict[str, Any] | None = None,
    ) -> dict[str, Any] | None:
        self.report.actions.append(action)
        if self.report.dry_run:
            return None
        kwargs: dict[str, Any] = {"body": body}
        if query:
            kwargs["query"] = query
        result: dict[str, Any] = self.api.do(method, path, **kwargs) or {}
        return result


def _same_target(current: Any, desired: dict[str, Any]) -> bool:
    if not isinstance(current, dict):
        return False
    return all(
        current.get(key) == value for key, value in desired.items() if value is not None
    )


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--profile", default="idp-mvp")
    parser.add_argument("--host", required=True)
    parser.add_argument("--app-name", default="idp-mvp")
    parser.add_argument("--target", required=True)
    parser.add_argument("--catalog", required=True)
    parser.add_argument("--project-schema", required=True)
    parser.add_argument("--table-prefix", help="Defaults to idp_<target>")
    parser.add_argument("--source-volume", default="idp_source")
    parser.add_argument(
        "--no-knowledge-assistant",
        action="store_true",
        help="Supervisor with the UC functions only (for workspaces where the KA is unavailable)",
    )
    parser.add_argument(
        "--dry-run", action="store_true", help="Read only; print planned changes"
    )
    args = parser.parse_args()
    from workspace_auth import plain_origin, workspace_client  # sibling script module

    settings = Settings(
        app_name=args.app_name,
        target=args.target,
        catalog=args.catalog,
        project_schema=args.project_schema,
        table_prefix=args.table_prefix or f"idp_{args.target}",
        source_path=f"/Volumes/{args.catalog}/{args.project_schema}/{args.source_volume}/incoming/",
        with_knowledge_assistant=not args.no_knowledge_assistant,
    )
    try:
        plain_origin(args.host)
        validate_settings(settings)
    except ValueError as error:
        parser.error(str(error))
    client = workspace_client(args.profile, args.host, http_timeout_seconds=60)
    report = Provisioner(client, settings, args.dry_run).run()
    print(json.dumps(report.__dict__, indent=2))


if __name__ == "__main__":
    main()
